DAY:
  title: "Day"
  description: "Light colored profile."
  rules:
    - kde.notify: "Switching to daylight profile..."
    - plasma.theme: "default"
    - plasma.wallpaper: "$KDEWALLPAPER/Castilla_Sky/"
    - kde.widget_style: "oxygen"
    - kde.colorscheme: "$KDEDATA/color-schemes/Oxygen.colors"
    - kde.notify: "Done!"
NIGHT:
  title: "Night"
  description: "Dark colored profile."
  rules:
    - kde.notify: "Switching to night profile..."
    - plasma.theme: "oxygen"
    - plasma.wallpaper: "$KDEWALLPAPER/Prato/"
    - kde.widget_style: "cleanlooks"
    - kde.colorscheme: "$KDEDATA/color-schemes/WontonSoup.colors"
    - kde.notify: "Done!"
