DAY:
  title: "Day"
  description: "Light colored profile."
  rules:
    - atomio.config_find_replace:
      - "one-dark-ui"
      - "atom-light-ui"
    - atomio.config_find_replace:
      - "solarized-dark-syntax"
      - "solarized-light-syntax"
    # - plasma.wallpaper: "$HOME/doc/pic/wallpaper/rotterdam/centraal.jpg"
    - plasma.wallpaper: "$HOME/doc/pic/wallpaper/Nature/lavender-field.jpg"
    # - plasma.wallpaper: "$HOME/doc/pic/wallpaper/rotterdam/1498967_866539266745416_4122185541686443994_o.jpg"
    - plasma.colorscheme: "$KDEDATA/color-schemes/SoftMetalColder.colors"
    - konsole.default_profile:
      - "day.profile"
      - konsole.restart:
    - yakuake.default_profile:
       - "day.profile"
       - yakuake.restart:
         - call.script: "$HOME/.config/autostart/yakuake.sh"
NIGHT:
    title: "Night"
    description: "Dark colored profile."
    rules:
      - atomio.config_find_replace:
        - "atom-light-ui"
        - "one-dark-ui"
      - atomio.config_find_replace:
        - "solarized-light-syntax"
        - "solarized-dark-syntax"
      - plasma.wallpaper: "$KDEWALLPAPER/Prato/"
      - plasma.colorscheme: "$KDEDATA/color-schemes/ObsidianCoast.colors"
      - konsole.default_profile:
        - "night.profile"
        - konsole.restart:
      - yakuake.default_profile:
         - "night.profile"
         - yakuake.restart:
           - call.script: "$HOME/.config/autostart/yakuake.sh"
